### PR TITLE
Add base

### PR DESCRIPTION
**Pull request by bodepd**

### CODE REVIEW

**Comment by bodepd** [comment]
I wanted to make a couple of comments here b/c this is one of the first commits related to the data refactor.

Part of the data model refactor involves taking all code out of the site manifests and implementing it as classes in modules. There will be several commit besides this one that accomplish this task for various parts of the current code in core.pp.

I am not entirely sure where this code goes (top level Cisco specific code that is required to deploy COSI). I had previously created COI for this purpose, but it's a bit coupled with hiera, and not currently used outside of the openstack-installer tool.

I chose to put this class here to try to bridge the data model work to the current efforts around the grizzly manifests code.

I targeted this against the grizzly branch (even though in theory, it should be targeted against havana) b/c
1. The current havana branch seems to be out of date
2. Since it is compatible with the existing Puppet code, it could be usable with the grizzly manifests.

I could alternatively have put this code in puppet-coi (and already had a variation of it coi::profiles::openstack::base), but I am concerned that code that goes there has been bit-rotting.

**Comment by robertstarmer** [comment]
:+1:

**Comment by rickerc** [comment]
I think we'd really prefer all this be done against havana and not risk destabilizing grizzly with a major code refactor at this point

if havana branches of the module at hand are out of date just update them as applicable. havana currently doesn't work so you won't break anything by doing so

**Comment by bodepd** [comment]
@rickerc to clarify, I was not planning on changing anything, or removing anything from the repos. Just adding classes. I can look at updating the havana branches for this repo.

**Pull request merged**
