### PR TITLE
Ensure cisco plugin dir exists before making creds

### PR DESCRIPTION
**Pull request by michaeltchapman**

### CODE REVIEW

**Comment by rickerc** [comment]
+1

**Comment by robertstarmer** [comment]
:+1:

**Comment by shmcfarl** [comment]
I applied the patch and now this comes up: 
err: /Stage[main]/Coe::Nexus/File[/etc/quantum/plugins/cisco/nexus.ini]/ensure: change from absent to file failed: Could not set 'file on ensure: No such file or directory - /etc/quantum/plugins/cisco/nexus.ini.puppettmp_9855 at /usr/share/puppet/modules/coe/manifests/nexus.pp:16

**Comment by shmcfarl** [comment]
It must have been a puppet ordering situation. I re-ran after a clean build and it is all good now. I get no more errors after this patch. Thanks.

**Pull request merged**
