### PR TITLE
Notify

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by markvoelker** [comment]
+1

**Comment by iawells** [comment]
I have no objections to any of the patches but both of the ones that say 'perms on keyring' have nothing to do with permissions and fix missing dependencies, and are therefore misdescribed.  So we care sufficiently?

**Comment by iawells** [comment]
The 'copy the key to make cinder/glance work' are not specific to either Cinder or Glance - they just put the key in a place where clients expect to find it.  Could arguably be part of puppet-ceph if implemented that way.

**Comment by ghost** [comment]
the second perms commit does affect permissions. regardless I think this is a non-issue for now.

**Comment by robertstarmer** [comment]
:+1:  Still need to test

**Pull request merged**
