### PR TITLE
Bug 1216032 - missing dependency on parent dir

### PR DESCRIPTION
**Pull request by rickerc**
Add parent dir to ensure it is present before files are created

### CODE REVIEW

**Comment by markvoelker** [comment]
+1

**Comment by markvoelker** [comment]
Hmm...actually, shouldn't the files have a dependency on the directory?

**Comment by rickerc** [comment]
puppet automagically adds dependencies between any file resources it manages

more correctly, puppet automatically adds the dependency on the dir if the dir and the file under it are both managed by it

**Comment by pkilambi** [comment]
:+1:

**Pull request merged**
