### PR TITLE
Ceph cinder-volume multihost fix

### PR DESCRIPTION
**Pull request by ghost**
This allows N number of cinder-volume nodes to use the RBD backend.

### CODE REVIEW

**Comment by ghost** [comment]
that was my first commit, I removed the $. Both that and @ work IIRC. I've tested it on two nodes as it stands now, with success.

**Comment by rickerc** [comment]
It should be '@fsid' -- 'fsid' is deprecated with Puppet 3.x

**Comment by rickerc** [comment]
With this I still get failure to attach a ceph-backed cinder volume on any compute other than the first. Error logged is

2013-08-07 04:21:36.195 30048 TRACE nova.openstack.common.rpc.amqp libvirtError: internal error rbd username 'admin' specified but secret not found

**Comment by ghost** [comment]
chris, ensure that 'virsh secret-list' shows your secret on both hosts and that cinder has the rbd_secret_uuid set. Be sure to bounce nova-compute and cinder-volumes on both servers. I've tested this on two compute nodes. Created volumes on each node, and attached to vms on each node. Check out my pod if you need a comparitive config.

**Comment by ghost** [comment]
I'll change it to '@'. We need to change our other templates too I believe.

**Comment by rickerc** [comment]
+1

Tested again with completely fresh install (rather than existing install + "add a node after") and all looks good. Brought a VM up on each node, made volumes, mounted to VMs on each node, unmounted, mounted to VMs on the other node

**Comment by markvoelker** [comment]
+1

**Pull request merged**
