### PR TITLE
Make coe::nexus work with Havana

### PR DESCRIPTION
**Pull request by markvoelker**
The coe::nexus class was still referring to OpenStack
Networking as Quantum.  Since the name was changed to
Neutron in Havana, we need to follow suit.  This patch
changes all references from Quantum to Neutron.

Additionally, the configuration files for the Cisco plugins
have changed in Havana.  This patch provides a new template
and appropriate logic to populate it.

Partial-Bug: #1276168

Note to reviewers: 
This is WIP.  There is likely a patch to puppet-neutron needed to clean up some stale-but-harmless config as well, and a corresponding patch to puppet_openstack_builder too.  In the interim you can try this out by doing the following:

In /etc/puppet/data/global_hiera_params/common.yaml, set:

```
tenant_network_type: vlan
```

In /etc/puppet/data/class_groups/network_controller.yaml, add:

```
  - "coe::nexus"
  - "%{network_service}::plugins::cisco"
```

In /etc/puppet/data/hiera_data/user.common.yaml add something like (yes, there's still some redundant info in there as of right now):

```
neutron::core_plugin: 'neutron.plugins.cisco.network_plugin.PluginV2'
neutron::plugins::cisco::database_name: 'neutron'
neutron::plugins::cisco::database_pass: 'quantum_pass'
neutron::plugins::cisco::database_user: 'neutron'
neutron::plugins::cisco::database_host: '192.168.255.134'
neutron::plugins::cisco::keystone_password: 'quantum_pass'
neutron::plugins::cisco::keystone_username: 'neutron'
neutron::plugins::cisco::keystone_tenant: 'services'
neutron::plugins::cisco::keystone_auth_url: 'http://control-host.domain.name:5000/v2.0/'
neutron::plugins::vlan_start: 500
neutron::plugins::vlan_end: 600
neutron::plugins::cisco::nexus_plugin: 'neutron.plugins.cisco.nexus.cisco_nexus_plugin_v2.NexusPlugin'
neutron::plugins::cisco::vswitch_plugin: 'neutron.plugins.openvswitch.ovs_neutron_plugin.OVSNeutronPluginV2'
neutron::plugins::ovs::network_vlan_ranges: 'physnet1:500:600'
neutron::agents::ovs::bridge_uplinks:
  - 'br-eth1:eth1'
neutron::agents::ovs::bridge_mappings:
  - 'physnet1:br-eth1'
coe::nexus::nexus_credentials:
  - '192.168.2.81/admin/password'
  - '192.168.2.82/admin/password'
coe::nexus::nexus_config:
  'switch1':
    'ip_address': '192.168.2.81'
    'username': 'admin'
    'password': 'password'
    'ssh_port': 22
    'servers':
      'server1': '1/1'
      'server2': '1/2'
  'switch2':
    'ip_address': '192.168.2.82'
    'username': 'admin'
    'password': 'password'
    'ssh_port': 22
    'servers':
      'server3': '1/3'
```

Here's a reference for how the config should end up looking:
https://wiki.openstack.org/wiki/Cisco-neutron

### CODE REVIEW

**Comment by pkilambi** [comment]
:+1: looks good on first glance. I'll try to find some hardware and take this for a spin when i get a chance.

**Comment by shwetaap** [comment]
So one of the issues we see is that the neutron-server starts by using just the cisco_plugins.ini config file. It does not use the ovs_neutron_plugin.ini config file. And so throws an error while network creation. 
The solutions as discussed was to have either the neutron server start using both these files or shift the config parameters in ovs_neutron_plugin.ini  to cisco_plugins.ini
https://wiki.openstack.org/wiki/Cisco-neutron#Basic_Plugin_Configuration

**Comment by shwetaap** [comment]
The second issue is while creation of an instance. This is the error stack trace in the neutron-server log
2014-03-05 14:53:35.866 22102 TRACE neutron.api.v2.resource 
2014-03-05 14:54:14.491 22102 ERROR neutron.api.v2.resource [-] create failed
2014-03-05 14:54:14.491 22102 TRACE neutron.api.v2.resource Traceback (most recent call last):
2014-03-05 14:54:14.491 22102 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/api/v2/resource.py", line 84, in resource
2014-03-05 14:54:14.491 22102 TRACE neutron.api.v2.resource     result = method(request=request, *_args)
2014-03-05 14:54:14.491 22102 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/api/v2/base.py", line 405, in create
2014-03-05 14:54:14.491 22102 TRACE neutron.api.v2.resource     obj = obj_creator(request.context, *_kwargs)
2014-03-05 14:54:14.491 22102 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/plugins/cisco/models/virt_phy_sw_v2.py", line 322, in create_port
2014-03-05 14:54:14.491 22102 TRACE neutron.api.v2.resource     context, tenant_id, net_id, instance_id, host_id)
2014-03-05 14:54:14.491 22102 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/plugins/cisco/models/virt_phy_sw_v2.py", line 280, in _invoke_nexus_for_net_create
2014-03-05 14:54:14.491 22102 TRACE neutron.api.v2.resource     [network, attachment])
2014-03-05 14:54:14.491 22102 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/plugins/cisco/models/virt_phy_sw_v2.py", line 149, in _invoke_plugin_per_device
2014-03-05 14:54:14.491 22102 TRACE neutron.api.v2.resource     device_params)]
2014-03-05 14:54:14.491 22102 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/plugins/cisco/models/virt_phy_sw_v2.py", line 171, in _invoke_plugin
2014-03-05 14:54:14.491 22102 TRACE neutron.api.v2.resource     return func(*args)
2014-03-05 14:54:14.491 22102 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/plugins/cisco/nexus/cisco_nexus_plugin_v2.py", line 89, in create_network
2014-03-05 14:54:14.491 22102 TRACE neutron.api.v2.resource     raise cisco_exc.NexusComputeHostNotConfigured(host=host)
2014-03-05 14:54:14.491 22102 TRACE neutron.api.v2.resource NexusComputeHostNotConfigured: Connection to compute-server01 is not configured.

I see the following setup in the cisco_plugin.ini
[switch1:172.20.231.66]
compute-server03=1/14
compute-server02=1/5
compute-server01=1/3
ssh_port=22

**Comment by markvoelker** [comment]
Yeah, the init script thing is annoying: Ubuntu's init scripts are kind of dumb in that they assume one plugin config file.  I'm working on a possible workaround for that which I'll submit separately (or it may just end up as a packaging change).  We're likely to run into the same issue with a couple of other things (like FWaaS).

**Comment by markvoelker** [comment]
Ok, the traceback should be resolved with the update I just pushed in.  The problem was that the plugin is now looking for:

```
[NEXUS_SWITCH:172.20.231.66]
```

E.g. it wants the string literal NEXUS_SWITCH, not a switch name.  A one-line change to the erb template fixes that.

**Comment by shwetaap** [comment]
+1. Works on my setup

**Comment by rickerc** [comment]
+1

**Pull request merged**
