### PR TITLE
Replace build node index.html page

### PR DESCRIPTION
**Pull request by rickerc**
- Generate a slightly more useful index.html on the build node
- Provide links to the various supplied web interfaces so users can find nagios, graphite, etc easily

### CODE REVIEW

**Comment by robertstarmer** [comment]
:+1: 

Still want to test, but there doesn't look like anything that would break with this (and it's very much needed).

**Comment by rickerc** [comment]
Also requires one other pull request -- small addition to core.pp to load the new module

https://github.com/CiscoSystems/folsom-manifests/pull/41

**Comment by cbaesema** [comment]
:+1:

Tested pull recommend merge

**Comment by robertstarmer** [comment]
:0:

As was pointed out to me on a change to the Horizon resource, this should be implemented as a sites-avaiable sites-enabled module for apache rather than as a rewrite of an index file.

Not against this, but I think we could consider re-writing before migrating to the Cisco repos.

R
On Feb 27, 2013, at 5:39 AM, Chip <notifications@github.com<mailto:notifications@github.com>>
 wrote:

[:+1:]

Tested pull recommend merge

**Comment by cbaesema** [comment]
Does a rewrite using sites-available complicate a future redhat platform target?

**Comment by rickerc** [comment]
RH doesn't machine Apache to nearly the extent Debian does. Anything doing Apache will have to be abstracted out and forked to deal with both...

It's no big deal to do this either way but I'm not sure what it would get us. This essentially is rewriting the index.html content which is put down by the default site-available, and is intended to be overwritten like that...

**Comment by robertstarmer** [comment]
Ok, works.

R
On Feb 27, 2013, at 9:26 AM, Chris Ricker <notifications@github.com<mailto:notifications@github.com>> wrote:

RH doesn't machine Apache to nearly the extent Debian does. Anything doing Apache will have to be abstracted out and forked to deal with both...

It's no big deal to do this either way but I'm not sure what it would get us. This essentially is rewriting the index.html content which is put down by the default site-available, and is intended to be overwritten like that...

**Comment by rickerc** [comment]
solution to 1152240

**Pull request merged**
