### PR TITLE
Allow mons on compute

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by markvoelker** [comment]
I tested this and https://github.com/CiscoSystems/grizzly-manifests/pull/167 together in a 5-node testbed.  Mon0 on the controller, mon1 on compute01, mon2 on compute02, osd on compute03.  I have $osd_on_compute = false and $computes_have_mons = true.  I'm seeing the following on all the mon and osd nodes:

Aug 29 04:51:59 compute03 puppet-agent[4545]: Failed to apply catalog: Could not find dependency Ceph::Key[admin] for Exec[copy the admin key to make cinder work] at /usr/share/puppet/modules/coe/manifests/ceph/compute.pp:46

This continues on every puppet run, even after the controller has completed more than 4 catalog runs.  On the fourth catalog run on the controller I see:

Aug 29 04:50:41 control01 puppet-agent[9096]: (/Stage[main]/Ceph_mon/Ceph::Mon[0]/Exec[ceph-admin-key]/returns) change from notrun to 0 failed: Command exceeded timeout at /usr/share/puppet/modules/ceph/manifests/mon.pp:96
Aug 29 04:50:41 control01 puppet-agent[9096]: (/Stage[main]/Coe::Ceph::Control/File[/etc/ceph/keyring]) Dependency Exec[ceph-admin-key] has failures: true
Aug 29 04:50:41 control01 puppet-agent[9096]: (/Stage[main]/Coe::Ceph::Control/File[/etc/ceph/client.admin]) Dependency Exec[ceph-admin-key] has failures: true
Aug 29 04:50:41 control01 puppet-agent[9096]: (/Stage[main]/Coe::Ceph::Control/Exec[create the pool]) Dependency Exec[ceph-admin-key] has failures: true
Aug 29 04:51:34 control01 puppet-agent[9096]: (/Stage[main]/Glance::Registry/Service[glance-registry]) Dependency Exec[ceph-admin-key] has failures: true
Aug 29 04:51:34 control01 puppet-agent[9096]: (/Stage[main]/Glance::Api/Service[glance-api]) Dependency Exec[ceph-admin-key] has failures: true
Aug 29 04:57:12 control01 puppet-agent[14188]: (/Stage[main]/Ceph_mon/Ceph::Mon[0]/Exec[ceph-admin-key]/returns) change from notrun to 0 failed: Command exceeded timeout at /usr/share/puppet/modules/ceph/manifests/mon.pp:96
Aug 29 04:57:12 control01 puppet-agent[14188]: (/Stage[main]/Coe::Ceph::Control/File[/etc/ceph/keyring]) Dependency Exec[ceph-admin-key] has failures: true
Aug 29 04:57:12 control01 puppet-agent[14188]: (/Stage[main]/Coe::Ceph::Control/File[/etc/ceph/client.admin]) Dependency Exec[ceph-admin-key] has failures: true
Aug 29 04:57:12 control01 puppet-agent[14188]: (/Stage[main]/Coe::Ceph::Control/Exec[create the pool]) Dependency Exec[ceph-admin-key] has failures: true
Aug 29 04:57:36 control01 puppet-agent[14188]: (/Stage[main]/Glance::Registry/Service[glance-registry]) Dependency Exec[ceph-admin-key] has failures: true
Aug 29 04:57:36 control01 puppet-agent[14188]: (/Stage[main]/Glance::Api/Service[glance-api]) Dependency Exec[ceph-admin-key] has failures: true
localadmin@control01:~$

**Comment by markvoelker** [comment]
Thanks @dontalton for the help troubleshooting and for finding an error in the site.pp file that may be causing the timeout.  I have a fresh build going now and will report back later today to see if that resolves the problem.

**Comment by markvoelker** [comment]
+1, looks like it was stale storeconfigs causing the issue I ran into earlier.

**Comment by rickerc** [comment]
+1

**Pull request merged**
