### PR TITLE
Fix glance

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by markvoelker** [comment]
What bug does this fix?  Could you specify the bug ID in your commit message?

**Comment by ghost** [comment]
@mark ceph::conf is declared elsewhere. " Ceph::Key['admin']" causes a catalog run failure, since it does not exist yet. And since multiple runs are necessary for the mon creation, the admin key gets copied in the process anyhow.

**Comment by markvoelker** [comment]
@dontalton: Ok, but what's the bug describing that?  There needs to be a bug in Launchpad so this shows up in our release changelog.

**Comment by ghost** [comment]
https://bugs.launchpad.net/openstack-cisco/+bug/1214414

**Comment by rickerc** [comment]
Is there another patch that goes with this one? This pull plus current manifests and modules means the controller never builds fully...

**Comment by ghost** [comment]
grab these also and you should be good, just ran them through the gamut

https://bugs.launchpad.net/openstack-cisco/+bug/1215087

**Comment by rickerc** [comment]
https://github.com/CiscoSystems/puppet-coe/pull/13
https://github.com/CiscoSystems/grizzly-manifests/pull/155

Are the two pulls referenced in that bug

With those three pulls, puppet runs smoothly but I get a traceback when using ceph-backed glance:

2013-08-22 19:55:38.083 ERROR glance.api.v1.images [07e38fe7-9b0c-43e6-b6ec-fbcb63cf23c5 18479d0a1fcd4248bef96281467f6217 f969497daaf34edc829bd4efb00e1413] Failed to upload image
2013-08-22 19:55:38.083 5090 TRACE glance.api.v1.images Traceback (most recent call last):
2013-08-22 19:55:38.083 5090 TRACE glance.api.v1.images   File "/usr/lib/python2.7/dist-packages/glance/api/v1/images.py", line 444, in _upload
2013-08-22 19:55:38.083 5090 TRACE glance.api.v1.images     image_meta['size'])
2013-08-22 19:55:38.083 5090 TRACE glance.api.v1.images   File "/usr/lib/python2.7/dist-packages/glance/store/rbd.py", line 241, in add
2013-08-22 19:55:38.083 5090 TRACE glance.api.v1.images     with rados.Rados(conffile=self.conf_file, rados_id=self.user) as conn:
2013-08-22 19:55:38.083 5090 TRACE glance.api.v1.images   File "/usr/lib/python2.7/dist-packages/rados.py", line 123, in __init__
2013-08-22 19:55:38.083 5090 TRACE glance.api.v1.images     self.conf_read_file(conffile)
2013-08-22 19:55:38.083 5090 TRACE glance.api.v1.images   File "/usr/lib/python2.7/dist-packages/rados.py", line 157, in conf_read_file
2013-08-22 19:55:38.083 5090 TRACE glance.api.v1.images     raise make_ex(ret, "error calling conf_read_file")
2013-08-22 19:55:38.083 5090 TRACE glance.api.v1.images Error: error calling conf_read_file: error code 22
2013-08-22 19:55:38.083 5090 TRACE glance.api.v1.images

**Comment by rickerc** [comment]
Rebased coe bits from https://github.com/CiscoSystems/puppet-coe/pull/13 to resolve conflics between the two

**Comment by rickerc** [comment]
For those testing, the combination of this pull and https://github.com/CiscoSystems/grizzly-manifests/pull/155 should work when ceph mon / osd are separate nodes from control / compute now

**Comment by rickerc** [comment]
This should also work for the use case of a combined mon+controller now

**Comment by pkilambi** [comment]
+1

**Pull request merged**
