### PR TITLE
Remove uuid injection, added cinder standalone class

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by markvoelker** [comment]
One of these addresses a bug I believe, the other doesn't.  Could we split them out?

**Comment by iawells** [comment]
The cinder standalone package - why's it suddenly need adding?  I thought it was already there.

**Comment by ghost** [comment]
it's not in puppet-coe

@mark, do you mean an actual bug? or a launchpad filed bug?

**Comment by markvoelker** [comment]
@dontalton : yes, an actual Launchpad bug.  1b1402 looks like it's trying to address bug 1211855 (though the commit message doesn't say...best practice would probably be to follow https://wiki.openstack.org/wiki/GitCommitMessages#Summary_of_GIT_commit_message_structure ideally).  8d6253c looks unrelated to that bug and looks like it's trying to address something else that I don't see a bug or blueprint for.

**Pull request closed without merging**
