### PR TITLE
ml2 hack

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
solves https://bugs.launchpad.net/openstack-cisco/+bug/1322012

**Comment by ghost** [comment]
related POB upstream patch
https://review.openstack.org/97368

**Comment by rickerc** [comment]
This blows up in distributed scenarios (2_role or full_ha) where the compute and control are separate

In that case, it works on the control, but on the compute errors with:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: File_line[change default file] { require => Package[neutron-server] }, because Package[neutron-server] doesn't seem to be in the catalog
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by rickerc** [comment]
This got neutron running in the aio case though. Will try compressed_ha next

**Comment by ghost** [comment]
Ah I can see that. It made sense to shove it coe::base since that's already called everywhere.I was trying to dodge adding a new class to all the roles. Open to ideas.

**Comment by rickerc** [comment]
you could do the "if it's in the catalog" voodoo around the relationship but that's really hard to read. Hopefully there's a better option

**Comment by ghost** [comment]
i agree...would sticking it in network_controller suffice?

**Comment by ghost** [comment]
I haven't found a clear answer, but I'm giving defined() a run. The question is whether or not defined()   is validated after the whole catalog is constructed or not.

**Comment by rickerc** [comment]
defined still goes boom:

Error: Invalid relationship: File_line[change default file] { require => Package[neutron-server] }, because Package[neutron-server] doesn't seem to be in the catalog

**Comment by ghost** [comment]
closing in lieu of  https://github.com/CiscoSystems/puppet-neutron/pull/2

**Pull request closed without merging**
