### PR TITLE
added a class to handled combined ceph mon/osd services on a single node

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by markvoelker** [comment]
+1

**Comment by markvoelker** [comment]
I may have to withdraw that +1.  I'm noticing that on compute nodes, there's a different uuid in the output of virsh secret-list and in cinder.conf.  That means you'd be able to create volumes, but not attach them correctly.  That may well be a timing issue, and I'm not sure whether it's here or in https://github.com/CiscoSystems/grizzly-manifests/pull/174.

**Comment by markvoelker** [comment]
+1 with 1fd332e

**Comment by robertstarmer** [comment]
:+1:

**Pull request merged**
